name: stock_count
description: Stock count feature package
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  foundation:
    path: ../../foundation
  platform:
    path: ../../platform
  inventory:
    path: ../inventory

  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
