name: design_system
description: Design system package for accounting app
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  phosphor_flutter: ^2.0.0

  # State Management
  flutter_riverpod: ^2.4.9

  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
